config/routes.rb
Rails.application.routes.draw do

  get 'users/:id/dashboard',to: 'users#dashboard', as: 'dashboard'
  get 'users/:id/inbox',to: 'users#inbox', as: 'inbox'
  get 'users/:user_id/inbox/:id', to: 'users#conversation', as: 'inbox_users'
  get 'speakers', to: 'speakers#speaker_index'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms', to: 'pages#terms'
  get 'become', to: 'pages#become'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    resources :user_tags, only: [:create]
    patch 'speaker/create', to: 'speakers#speaker_create'
    get 'speaker/new', to: 'speakers#speaker_new'
    get 'speaker', to: 'speakers#speaker_show'
    get 'speaker/edit', to: 'speakers#speaker_edit'
    patch 'speaker/update', to: 'speakers#speaker_update'
    resources :user_bookings, only: [:index]
    resources :speaker_bookings, only: [:index]
    resources :messages, only: [:index, :new, :create]
    resources :invites, only: [:create]
    resources :photos, only: [:destroy]
    resources :user_photos, only: [:destroy]
    member do
      get 'messages/ajax'
    end
  end
  resources :user_tags, only: [:destroy]
  resources :events do
    resources :user_bookings, only: [:new, :create]
    resources :speaker_bookings, only: [:new, :create]
  end

  resources :user_bookings, only: [:destroy]

  resources :speaker_bookings, only: [:destroy]

  patch 'invite/:id/accept', to: 'invites#accept', as: 'invites_accept'
  patch 'invite/:id/reject', to: 'invites#reject', as: 'invites_reject'
  patch 'invite/:id/negotiate', to: 'invites#negotiate', as: 'invites_negotiate'

  mount ActionCable.server => "/cable"
end

app/models/user.rb
class User < ApplicationRecord
  include PgSearch
  module ActiveModel::Validations::HelperMethods
    def validates_email(*attr_names)
      validates_with EmailValidator, _merge_attributes(attr_names)
    end
  end
  before_create :capitalize_names
  after_create :send_welcome_email, :send_notification_email

  mount_uploader :photo, PhotoUploader
  has_many :events, dependent: :destroy
  has_many :user_bookings, dependent: :destroy
  has_many :speaker_bookings, dependent: :destroy
  has_many :user_tags, dependent: :destroy
  has_many :user_talks, dependent: :destroy
  has_many :categories, through: :user_tags
  has_many :talks, through: :user_talks
  has_many :user_photos, dependent: :delete_all
  has_many :invites, dependent: :destroy
  has_many :user_videos, dependent: :destroy
  accepts_nested_attributes_for :user_photos
  accepts_nested_attributes_for :user_videos

  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'receiver_id'
  geocoded_by :postcode
  monetize :cost_cents

  # validates :title, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true, if: :is_speaker?
  validates :postcode, presence: true, format: { with: /([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z]))))\s?[0-9][A-Za-z]{2})/ }, if: :is_speaker?
  validates :travel_distance, presence: true, if: :is_speaker?
  validates :cost, presence: true, if: :is_speaker?

  validates_email :email


  after_validation :geocode, if: :will_save_change_to_postcode?

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable, :omniauthable, omniauth_providers: %i[facebook]

  scope :cost, -> (cost) { where("cost_cents <= ?", cost.to_i * 100) }

  pg_search_scope :search_by_full_name,
  against: [ :first_name, :last_name ],
  using: {
    tsearch: { prefix: true }
  }

  def is_speaker?
    self.is_speaker
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  private

  def capitalize_names
    self.first_name = first_name.capitalize
    self.last_name = last_name.capitalize
  end

  def send_welcome_email
    UserMailer.welcome(self).deliver_now!
  end

  def send_notification_email
    UserMailer.new_user(self).deliver_now!
  end

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.first_name = auth.info.first_name
        user.last_name = auth.info.last_name
        user.remote_photo_url = auth.info.image # assuming the user model has an image
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        user.skip_confirmation!
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      redirect_to new_user_registration_path(active_tab: 'signup')
      if resource.email? == false
        set_flash_message :notice, :error
      elsif resource.email == User.find_by_email(resource.email).email
        set_flash_message :notice, :already
      else
        set_flash_message :notice, :error
      end
    end
  end

  private

  def build_resource(hash = {})
    self.resource = resource_class.new_with_session(hash, session)
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end


  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  protected

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
    resource.pending_reconfirmation? &&
    previous != resource.unconfirmed_email
  end

  # By default we want to require a password checks on update.
  # You can overwrite this method in your own RegistrationsController.
  def update_resource(resource, params)
    resource.update_with_password(params)
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash = {})
    self.resource = resource_class.new_with_session(hash, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    scope = Devise::Mapping.find_scope!(resource)
    router_name = Devise.mappings[scope].router_name
    context = router_name ? send(router_name) : self
    context.respond_to?(:root_path) ? context.root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    signed_in_root_path(resource)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", force: true)
    self.resource = send(:"current_#{resource_name}")
  end

  def sign_up_params
    devise_parameter_sanitizer.sanitize(:sign_up)
  end

  def account_update_params
    devise_parameter_sanitizer.sanitize(:account_update)
  end

  def translation_scope
    'devise.registrations'
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

  def create
    resource = warden.authenticate!(scope: resource_name, recall: 'users/sessions#redirect_after_failure')
    set_flash_message :notice, :signed_in
    sign_in_and_redirect(resource_name, resource)
  end

  def redirect_after_failure
    redirect_to new_user_session_path(active_tab: 'login')
    set_flash_message :alert, :error
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:dashboard, :show, :inbox, :edit, :update, :full_name]
  before_action :authorize_user, only: [:dashboard, :show, :inbox, :edit, :update]


  def dashboard
    @correspondents = assign_correspondents(@user)
  end

  def inbox
  end

  def conversation
    @user = User.find(params[:user_id])
    authorize @user
    @correspondent = User.find(params[:id])
    @messages = policy_scope(Message)
    @messages = @messages.where('sender_id = ? OR receiver_id = ?', params[:id], params[:id]).order(:created_at)
  end

  def index
    @users = User.all
    authorize @user
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to dashboard_path(@user) }
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'shared/user_profile' }
        format.js
      end
    end
  end


  #   if @user.update(user_params)
  #     redirect_to user_path(@user)
  #   else
  #     render :new
  #   end
  # end

  private

  def assign_correspondents(user)
    sent = user.sent_messages
    sent = sent.map { |message| [message.receiver, message.created_at] }
    received = user.received_messages
    received = received.map { |message| [message.sender, message.created_at] }
    correspondents = sent + received
    correspondents.sort_by! { |array| array[1] }
    correspondents.map! { |array| array[0] }
    correspondents.reverse!.uniq!
    correspondents.map do |correspondent|
      last_message = find_last_message(user, correspondent)
      [correspondent, last_message]
    end
  end

  def find_last_message(user, correspondent)
    sent = user.sent_messages.where(receiver: correspondent).last
    received = user.received_messages.where(sender: correspondent).last
    if sent.nil?
      received
    elsif received.nil?
      sent
    else
      sent.created_at > received.created_at ? sent : received
    end

  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :job_title, :description, :phone_number, :twitter, :photo, :photo_cache, {photo: []}, :location, :about, :address, :city, :postcode, :provider, :uid)
  end

  def authorize_user
    authorize @user
  end

end

app/views/users/conversation.html.erb
<div class="message-container">
  <div id="new-message">
    <%= link_to 'Send a message', messages_ajax_user_path(@correspondent), class: 'btn btn-primary', id:'message-btn', remote: true %>
  </div>
  <div id="message-list">
    <% @messages.reverse_order.each do |message| %>
      <% if message.sender == @user %>
        <%= render 'shared/sent_message', {message: message} %>
      <% else %>
        <%= render 'shared/received_message', {message: message} %>
      <% end %>
    <% end %>
  </div>
</div>
<% content_for :after_js do %>
  <script>
    App['conversation_<%= @user.id %>_<%= @correspondent.id %>'] = App.cable.subscriptions.create(
      { channel: 'ConversationChannel', sender_id: <%= @user.id %>, receiver_id: <%= @correspondent.id %> },
      { received: (data) => {
        const list = document.getElementById('message-list')
        list.insertAdjacentHTML('afterbegin', data.message_partial)
      }})
  </script>
<% end %>

app/views/users/conversation.js.erb
function refreshMessages() {
  const messages = document.getElementById('message-list')
  messages.innerHTML = ""
  <% @messages.each do |message| %>
    newMessage = '<%= j render 'shared/message', {message: message} %>'
    messages.insertAdjacentHTML('afterbegin', newMessage)
  <% end %>
}

refreshMessages()

app/views/users/dashboard.html.erb
<div class="dashboard-wrapper">
  <div class="dashboard-title">
    <h1>Welcome <%= current_user.first_name %></h1>
  </div>
  <div class="dashboard-container">
    <div class="dashboard-col-1">
      <% image = @user.photo.url ? @user.photo : "https://res.cloudinary.com/montycat/image/upload/v1520001176/profile-placeholder.png" %>
      <div id="img_prev" class="user-show-photo" style="background-image: url('<%= cl_image_path image, quality: "auto:low"; %>')">
      </div>
      <%= simple_form_for(@user, html: { method: :put }) do |f| %>
      <div class="change-photo-button">
        <%= f.input :photo, label: "Change Photo", class: 'upload-button', input_html: { id: "photo-input" } %>
        <%= f.input :photo_cache, as: :hidden %>
        <div class="form-actions">
          <%= f.button :submit, "Save", class: "photo-save-btn" %>
        </div>
      </div>
      <% end %>
      <ul class="navigation-area nav nav-tabs nav-stacked" role="tablist">
        <li role="presentation" class="dash-tab <%= (params[:active_tab] == nil) || (params[:active_tab] == 'profile') ? 'active' : '' %>"><a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><i class="fa fa-fw fa-user"></i> Profile</a></li>
        <li role="presentation" class="dash-tab <%= params[:active_tab] == 'messages' ? 'active' : '' %>"><a href="#messages" aria-controls="messages" role="tab" data-toggle="tab"><i class="fa fa-fw fa-envelope"></i> Messages</a></li>
        <li role="presentation" class="dash-tab <%= params[:active_tab] == 'events' ? 'active' : '' %>"><a href="#events" aria-controls="events" role="tab" data-toggle="tab"><i class="fa fa-fw fa-calendar"></i> Events</a></li>
        <% if current_user.is_speaker? %>
        <li role="presentation" class="dash-tab <%= params[:active_tab] == 'speaker-profile' ? 'active' : '' %>"><a href="#speaker-profile" aria-controls="speaker-profile" role="tab" data-toggle="tab"><i class="fa fa-fw fa-microphone"></i> Speaker Area</a></li>
        <% end %>
        <li role="presentation" class="dash-tab <%= params[:active_tab] == 'account' ? 'active' : '' %>"><a href="#account" aria-controls="account" role="tab" data-toggle="tab"><i class="fa fa-fw fa-wrench"></i> Account</a></li>
      </ul>
    </div>
    <div class="dashboard-col-2">
      <div class="tab-content-container">
        <div class="tab-content">
          <div name="profile" role="tabpanel" class="tab-pane <%= (params[:active_tab] == nil) || (params[:active_tab] == 'profile') ? 'active' : '' %>" id="profile">
            <%= render 'users/shared/profile-edit' %>
          </div>
          <div role="tabpanel" class="tab-pane <%= params[:active_tab] == 'messages' ? 'active' : '' %>" id="messages">
            <%= render 'shared/inbox-container' %>
          </div>
          <div role="tabpanel" class="tab-pane <%= params[:active_tab] == 'events' ? 'active' : '' %>" id="events">
            <%= render 'shared/user-events-list' %>
          </div>
          <div role="tabpanel" class="tab-pane <%= params[:active_tab] == 'account' ? 'active' : '' %>" id="account">
            <p>Change your password or email address</p>
            <%= link_to "Change Password", edit_user_registration_path, class: "navbar-sparks-item navbar-sparks-link" %>
            <h3>Cancel my account</h3>

            <p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>
          </div>
          <% if current_user.is_speaker? %>
          <div role="tabpanel" class="tab-pane <%= params[:active_tab] == 'speaker-profile' ? 'active' : '' %>" id="speaker-profile">
            <%= render 'shared/speaker-details', user: @user %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="edit-user-wrapper">
  <div class="edit-user-container">
    <h2>Edit <%= resource_name.to_s.humanize %></h2>

    <%= simple_form_for(@user, html: { method: :put }) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.input :first_name, required: true %>
      <%= f.input :last_name, required: true %>
      <%= f.input :email, required: true, autofocus: true %>

      <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
      <p>Currently waiting confirmation for: <%= resource.unconfirmed_email %></p>
      <% end %>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Update" %>
    </div>
    <% end %>

    <h3>Cancel my account</h3>

    <p>Unhappy? <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete %></p>

    <%= link_to "Back", :back %>
  </div>
</div>

app/views/users/inbox.html.erb
<div class="inbox-container">
  <% @correspondents.each do |correspondent| %>
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
      <div class="sender">
        <div class="sender-image">
          <img class="avatar-large" src="https://kitt.lewagon.com/placeholder/users/gabriel-dehan" style="width:70px;height:70px;border-radius: 50px">
        </div>
        <div class="sender-info">
          <p><%= link_to correspondent.email, inbox_users_path(@user, correspondent) %></p>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="user-show-wrapper">
  <div class="user-show-container">
    <div class="user-show-col-1">
      <% image = @user.photo.url ? @user.photo : "https://res.cloudinary.com/montycat/image/upload/v1520001176/profile-placeholder.png" %>
      <div class="user-show-photo" style="background-image: url('<%= cl_image_path image %>')">
      </div>
      <div class="user-show-verified-info">
        <div class="verified-heading">
          <p>Verified Info</p>
        </div>
        <div class="verified-info">
          <p>Email Address <% if @user.confirmed_at %><span><i class="far fa-check-circle"></i></span><% end %></p>
          <p>Phone Number<% if @user.phone_number %><span><i class="far fa-check-circle"></i></span><% end %></p>
          <% if @user.is_speaker %><p>Speaker</%><span><i class="far fa-check-circle"></i></span><% end %></p>
        </div>
      </div>
      <div class="user-show-verified-info">
        <div class="verified-heading">
          <p>About</p>
        </div>
        <div class="verified-info">
          <div class="user-show-job">
            <h5>Job Title</h5>
            <p><%= @user.job_title ? @user.job_title : "None" %></p>
          </div>
          <div class="user-show-city">
            <h5>City</h5>
            <p><%= @user.city ? @user.city : "None" %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="user-show-col-2">
      <div class="user-show-name">
        <h2><%= @user.full_name %></h2>
        <h5>Member Since - <%= @user.created_at.strftime("%B %Y") %></h5>
        <% if current_user == @user %>
        <%= link_to "Edit Profile", dashboard_path(current_user, active_tab: 'profile') %>
        <% end %>
      </div>
      <div class="user-show-description">
        <h3>About</h3>
        <p><%= @user.about ? @user.about : "No description added" %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/update.js.erb
// function refreshForm(innerHTML) {
//   const newBioForm = document.getElementById('formTarget');
//     newBioForm.innerHTML = innerHTML;
// };
function updateUser() {
  const name = document.getElementById('users-name');
  const newFirstName = document.getElementById('user_first_name').value
  const newLastName = document.getElementById('user_last_name').value
  name.innerText = newFirstName + ' ' + newLastName;


  const city = document.getElementById('users-city')
  const newCity = document.getElementById('user_city').value
  city.innerText = newCity


  const about = document.getElementById('users-about')
  const newAbout = document.getElementById('user_about').value
  about.innerText = newAbout
  // bio.insertAdjacentHTML('afterend', bioHTML);
  // const bioBox = document.querySelector('.box-profile-content p');
  // bioBox.remove();
};

updateUser();
// addBio("<%#= j render 'users/bio', user: @user %>");
// refreshForm("<%#= j render 'users/form', user: @user  %>");
console.log("hello user updated")