config/routes.rb
Rails.application.routes.draw do

  get 'users/:id/dashboard',to: 'users#dashboard', as: 'dashboard'
  get 'users/:id/inbox',to: 'users#inbox', as: 'inbox'
  get 'users/:user_id/inbox/:id', to: 'users#conversation', as: 'inbox_users'
  get 'speakers', to: 'speakers#speaker_index'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms', to: 'pages#terms'
  get 'become', to: 'pages#become'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    resources :user_tags, only: [:create]
    patch 'speaker/create', to: 'speakers#speaker_create'
    get 'speaker/new', to: 'speakers#speaker_new'
    get 'speaker', to: 'speakers#speaker_show'
    get 'speaker/edit', to: 'speakers#speaker_edit'
    patch 'speaker/update', to: 'speakers#speaker_update'
    resources :user_bookings, only: [:index]
    resources :speaker_bookings, only: [:index]
    resources :messages, only: [:index, :new, :create]
    resources :invites, only: [:create]
    resources :photos, only: [:destroy]
    resources :user_photos, only: [:destroy]
    member do
      get 'messages/ajax'
    end
  end
  resources :user_tags, only: [:destroy]
  resources :events do
    resources :user_bookings, only: [:new, :create]
    resources :speaker_bookings, only: [:new, :create]
  end

  resources :user_bookings, only: [:destroy]

  resources :speaker_bookings, only: [:destroy]

  patch 'invite/:id/accept', to: 'invites#accept', as: 'invites_accept'
  patch 'invite/:id/reject', to: 'invites#reject', as: 'invites_reject'
  patch 'invite/:id/negotiate', to: 'invites#negotiate', as: 'invites_negotiate'

  mount ActionCable.server => "/cable"
end

app/views/shared/_banner.html.erb
<div id="banner3" class="second-banner">
  <%= render 'shared/banner-navbar' %>
  <div class="banner" style="background-image: url(<%= cl_image_path('spker/main-banner.png', secure: "true") %>);">
    <!-- <div class="banner"> -->
    <div class="banner-content">
      <h1>the new way to book talented speakers</h1>
      <p>find speakers or become one today</p>
      <%= render 'shared/search-button' %>
      <%#= render 'shared/arrow' %>
    </div>
  </div>
<!--   <div class="speaker-cta">
    <h4>Register as a speaker today to get priority listing</h4>
    <%= link_to new_user_registration_path do  %>
    <button class="reg-button">Get Started</button>
    <% end %>
  </div> -->
</div>

app/views/shared/_carousel.html.erb
<div class="container" style="width: 50vw; height: 40%; ">
  <h2></h2>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" style="width: 100%; height: 60vh">
      <div class="item active">
        <img src="https://images.unsplash.com/photo-1517502884422-41eaead166d4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=3d8f17ce21e419f0ef0e90dfcbe19911&auto=format&fit=crop&w=2125&q=80" alt="test 1" style="width:100%; height:40%">
      </div>

      <div class="item">
        <img src="https://images.unsplash.com/photo-1479243396208-be1751535cdb?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=018516db30298c3f7677bd594891da5d&auto=format&fit=crop&w=2550&q=80" alt="test 2" style="width:100%; height:40%">
      </div>

      <div class="item">
        <img src="https://images.unsplash.com/photo-1492538368677-f6e0afe31dcc?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=c035f34c035a8690da777211f1e66d59&auto=format&fit=crop&w=2550&q=80" alt="test 3" style="width:100%; height:40%">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/shared/_event_card.html.erb
<div id="card-display">
  <div class="card-wrap scaled">
    <%= link_to event_path(event) do %>
    <img src="https://images.unsplash.com/photo-1517502884422-41eaead166d4?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=3d8f17ce21e419f0ef0e90dfcbe19911&auto=format&fit=crop&w=2125&q=80" alt="test 1" style="width:100%; height:60%">
    <div class="card-info">
      <div class="card-description">
        <h2><%= event.name %></h2>
        <p><%= event.address %></p>
        <p><%= event.postcode %></p>
        <p><%= event.cost %></p>
        <p><%= event.date %></p>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_invite-message-modal.html.erb
<div id="invite_modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Send invite</h4>
      </div>
      <div class="modal-body">
        <%= render 'shared/invite_form' %>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/shared/_map-vertical.html.erb
<div
  id="map"
  style="width: 100% !important;
  height: 100% !important;"
  data-markers="<%= @markers.to_json %>"
></div>

app/views/shared/_message_form.html.erb
<%= simple_form_for([user, message]) do |f| %>
  <%= f.input :content %>
  <%= f.button :submit, class: 'btn btn-primary', value: 'Send' %>
<% end %>

app/views/shared/_review_bar.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="well well-sm">
        <div class="row">
          <div class="col-xs-12 col-md-6 text-center">
            <h1 class="rating-num">
            4.0</h1>
            <div class="rating">
              <span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star">
              </span><span class="glyphicon glyphicon-star"></span><span class="glyphicon glyphicon-star">
              </span><span class="glyphicon glyphicon-star-empty"></span>
            </div>
            <div>
              <span class="glyphicon glyphicon-user"></span>1,050,008 total
            </div>
          </div>
          <div class="col-xs-12 col-md-6">
            <div class="row rating-desc">
              <div class="col-xs-3 col-md-3 text-right">
                <span class="glyphicon glyphicon-star"></span>5
              </div>
              <div class="col-xs-8 col-md-9">
                <div class="progress progress-striped">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
                  aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                  <span class="sr-only">80%</span>
                </div>
              </div>
            </div>
            <!-- end 5 -->
            <div class="col-xs-3 col-md-3 text-right">
              <span class="glyphicon glyphicon-star"></span>4
            </div>
            <div class="col-xs-8 col-md-9">
              <div class="progress">
                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
                aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                <span class="sr-only">60%</span>
              </div>
            </div>
          </div>
          <!-- end 4 -->
          <div class="col-xs-3 col-md-3 text-right">
            <span class="glyphicon glyphicon-star"></span>3
          </div>
          <div class="col-xs-8 col-md-9">
            <div class="progress">
              <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20"
              aria-valuemin="0" aria-valuemax="100" style="width: 40%">
              <span class="sr-only">40%</span>
            </div>
          </div>
        </div>
        <!-- end 3 -->
        <div class="col-xs-3 col-md-3 text-right">
          <span class="glyphicon glyphicon-star"></span>2
        </div>
        <div class="col-xs-8 col-md-9">
          <div class="progress">
            <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="20"
            aria-valuemin="0" aria-valuemax="100" style="width: 20%">
            <span class="sr-only">20%</span>
          </div>
        </div>
      </div>
      <!-- end 2 -->
      <div class="col-xs-3 col-md-3 text-right">
        <span class="glyphicon glyphicon-star"></span>1
      </div>
      <div class="col-xs-8 col-md-9">
        <div class="progress">
          <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80"
          aria-valuemin="0" aria-valuemax="100" style="width: 15%">
          <span class="sr-only">15%</span>
        </div>
      </div>
    </div>
    <!-- end 1 -->
  </div>
  <!-- end row -->
</div>
</div>
</div>
</div>
</div>
</div>

app/views/shared/_search-button.html.erb
<%= link_to speakers_path do  %>
<button class="search-button banner-search-btn">Find Speakers</button>
<% end %>

app/views/shared/_speaker-carousel.html.erb
<div class="container">
  <h2></h2>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->




    <% @user.user_photos.each_with_index do |photo, i|%>
      <% if i == 0 %>
      <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <% elsif @user.user_photos.count - 1 == i %>
        <li data-target="#myCarousel" data-slide-to="<%= i %>"></li>
        </ol>
      <% else %>
      <li data-target="#myCarousel" data-slide-to="<%= i %>"></li>
      <% end %>
    <% end %>
    <!-- </ol> -->


    <!-- Wrapper for slides -->
    <div class="carousel-inner" style="width:100%; height:100%">
      <% @user.user_photos.each_with_index do |photo, i| %>
      <% if i == 0  %>
        <div class="item active">
          <% image = photo.photo %>
          <%= image_tag(image) %>
        </div>
      <% elsif %>
      <div class="item">
        <% image = photo.photo %>
          <%= image_tag(image) %>
      </div>
      <% else %>
        <% image = current_user.photo.url ? current_user.photo : "https://res.cloudinary.com/montycat/image/upload/v1520001176/profile-placeholder.png" %>
        <%= image_tag(image)%>
      <% end %>
  <% end %>




    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/shared/_speaker_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.unsplash.com/photo-1505373877841-8d25f7d46678?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=f1d076508395c99b386351d72a95c09e&auto=format&fit=crop&w=2200&q=80');">
  <div class="banner-content">
    <h1>Welcome to spker</h1>
    <p>the easiest way to book a speaker</p>
    <form class="banner-searchform" action="/users">
      <input type="search" id="banner-searchbar" name="location"   placeholder="Country, City, Area, Postcode...">
      <button type="submit" class="btn btn-search-banner">Search</button>
    </form>
  </div>
</div>

app/views/shared/_user-carousel.html.erb
<div class="container" style="width: 50vw; height: 40%; ">
  <h2></h2>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" style="width: 100%; height: 60vh">
      <div class="item active">
        <%= cl_image_tag @user.photo, :crop => :crop , :width => 700 , :height => 600 , :gravity => :face %>
      </div>

      <div class="item">
        <img src="https://images.unsplash.com/photo-1505150892987-424388901632?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=84b47a91f3f340fbbf640f2ffc239c0a&auto=format&fit=crop&w=800&q=60" alt="test 2" style="width:100%; height:40%">
      </div>

      <div class="item">
        <img src="https://images.unsplash.com/photo-1503023345310-bd7c1de61c7d?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=cbeecdb7363ceb376809ec2a73cdaf09&auto=format&fit=crop&w=800&q=60" alt="test 3" style="width:100%; height:40%">
      </div>
      <div class="item">

      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/shared/_user-photo-loader.html.erb
<%= simple_form_for(@user, html: { method: :put }) do |f| %>
    <%= f.input :photo, class: 'upload-button' %>
    <%= f.input :photo_cache, as: :hidden, class: 'file-name' %>
    <%= f.button :submit, "Load image", class: 'load-image' %>
<% end %>

app/views/shared/_what-is.html.erb
<div class="what-is-wrapper">
  <div class="what-is-title">
    <h2>What is Spker?</h2>
    <p>Spker is a trusted community marketplace for public speakers and event organisers to find and book talented speakers in minutes</p>
  </div>
  <div class="what-is-icons">
    <div class="what-is-card">
      <div class="what-is-image" style="background-image: url(<%= cl_image_path("spker/colour-phones.jpg", quality: "auto:low", secure: "true") %>)"></div>
      <div class="what-is-card-detail">
        <h4>Out with the old</h4>
        <p>No middlemen, no phone calls, contact speakers directly</p>
      </div>
    </div>
    <div class="what-is-card">
      <div class="what-is-image" style="background-image: url(<%= cl_image_path("spker/colour-clock.jpg", quality: "auto:low", secure: "true") %>)"></div>
      <div class="what-is-card-detail">
        <h4>Ready when you are</h4>
        <p>Only see speakers available for your dates</p>
      </div>
    </div>
    <div class="what-is-card">
      <div class="what-is-image" style="background-image: url(<%= cl_image_path("spker/colour-stars.jpg", quality: "auto:low", secure: "true") %>)"></div>
      <div class="what-is-card-detail">
        <h4>Trust me</h4>
        <p>User curated reviews for your piece of mind</p>
      </div>
    </div>
  </div>
</div>