config/routes.rb
Rails.application.routes.draw do

  get 'users/:id/dashboard',to: 'users#dashboard', as: 'dashboard'
  get 'users/:id/inbox',to: 'users#inbox', as: 'inbox'
  get 'users/:user_id/inbox/:id', to: 'users#conversation', as: 'inbox_users'
  get 'speakers', to: 'speakers#speaker_index'
  get 'privacy_policy', to: 'pages#privacy_policy'
  get 'terms', to: 'pages#terms'
  get 'become', to: 'pages#become'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', sessions: 'users/sessions', registrations: 'users/registrations' }
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show, :edit, :update] do
    resources :user_tags, only: [:create]
    patch 'speaker/create', to: 'speakers#speaker_create'
    get 'speaker/new', to: 'speakers#speaker_new'
    get 'speaker', to: 'speakers#speaker_show'
    get 'speaker/edit', to: 'speakers#speaker_edit'
    patch 'speaker/update', to: 'speakers#speaker_update'
    resources :user_bookings, only: [:index]
    resources :speaker_bookings, only: [:index]
    resources :messages, only: [:index, :new, :create]
    resources :invites, only: [:create]
    resources :photos, only: [:destroy]
    resources :user_photos, only: [:destroy]
    member do
      get 'messages/ajax'
    end
  end
  resources :user_tags, only: [:destroy]
  resources :events do
    resources :user_bookings, only: [:new, :create]
    resources :speaker_bookings, only: [:new, :create]
  end

  resources :user_bookings, only: [:destroy]

  resources :speaker_bookings, only: [:destroy]

  patch 'invite/:id/accept', to: 'invites#accept', as: 'invites_accept'
  patch 'invite/:id/reject', to: 'invites#reject', as: 'invites_reject'
  patch 'invite/:id/negotiate', to: 'invites#negotiate', as: 'invites_negotiate'

  mount ActionCable.server => "/cable"
end

app/models/event.rb
class Event < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  belongs_to :user
  has_many :user_bookings, dependent: :destroy
  has_many :speaker_bookings, dependent: :destroy
  has_many :event_tags, dependent: :destroy
  has_many :event_talks, dependent: :destroy
  has_many :categories, through: :event_tags
  has_many :talks, through: :event_talks
  has_many :invites, dependent: :destroy
  has_many :photos
  geocoded_by :postcode

  validates :name, presence: true
  validates :address, presence: true
  validates :postcode, presence: true, format: { with: /([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9]?[A-Za-z]))))\s?[0-9][A-Za-z]{2})/ }
  validates :start_date, presence: true
  validates :end_date, presence: true

  after_validation :geocode, if: :will_save_change_to_postcode?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authorize_event, except: [:index, :new, :create, :update]

  def index
    if params[:location].nil? || params[:location] == ""
      @events = policy_scope(Event)
      authorize @events
      redirect_to root_path
    else
      @events = policy_scope(Event).near(params[:location], 10)
      filtering_params(params).each do |key, value|
        @events = @events.public_send(key, value) if value.present?
      end
      @markers = @events.map do |event| {
        lat: space.latitude,
        lng: space.longitude
      }
    end
  end
end

def show
  @markers = [ { lat: @event.latitude, lng: @event.longitude } ]
  @invite = @event.invites.find_by(user_id: current_user.id)
end

def new
  @event = Event.new
  authorize_event
end

def create
  @event = Event.new(event_params)
  authorize_event
  @event.user = current_user
  if @event.save
    generate_tags(params[:event][:category_ids], @event)
    generate_talks(params[:event][:talk_ids], @event)
    redirect_to event_path(@event)
  else
    render :new
  end
end

def edit
end

def update
  if @event.update(event_params)
    authorize_event
    @event.event_tags.each { |tag| tag.destroy }
    @event.event_talks.each { |talk| talk.destroy }
    generate_tags(params[:event][:category_ids], @event)
    generate_talks(params[:event][:talk_ids], @event)
    redirect_to event_path(@event)
  else
    render :edit
  end
end

def destroy
  @event.destroy
  redirect_to dashboard_path(current_user)
end

private

def generate_tags(ids, event)
  ids.each do |id|
    unless id.blank?
      tag = EventTag.new
      tag.category = Category.find(id)
      tag.event = event
      tag.save
    end
  end
end

def generate_talks(ids, event)
  ids.each do |id|
    unless id.blank?
      talk = EventTalk.new
      talk.talk = Talk.find(id)
      talk.event = event
      talk.save
    end
  end
end

def set_event
  @event = Event.find(params[:id])
end

def authorize_event
  authorize @event
end

def event_params
  params.require(:event).permit(:name, :address, :postcode, :start_date, :end_date, :expenses_hotels, :expenses_flights, :expenses_per_diems, :is_paid, :category_id, :talk_id, :photo, :description)
end

def filtering_params(params)
  params.slice(:address, :postcode)
end

end

app/views/events/edit.html.erb
<%= render 'shared/event_form', { user: @event.user, event: @event } %>

app/views/events/index.html.erb
<div class="main-container">
  <div class="body-container">
    <div class="card-container">
      <div class="events-title">
        <h4 id="index-header">Choose the perfect event space in <%= params[:location] %></h4>
      </div>
      <div class="row">
        <% @events.each do |event| %>
        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
          <%= render 'shared/card', event: event%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="map-container">
    <%= render 'shared/map-vertical' %>
  </div>
</div>

app/views/events/new.html.erb
<div class="event_form_container">
  <div class="form-box">
    <%= render 'shared/event_form', { user: @user, event: @event } %>
  </div>
</div>

app/views/events/show-old.html.erb
<%= render 'events/shared/event_quote_modal' %>
<div class="event-container">
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="info-container">
        <div class="basic-info">
          <div class="event-title">
            <h4><%= @event.name %></h4>
            <div class="organiser">
              <p>Organised by <%= @event.user.first_name %>  <%= @event.user.last_name %></p>
              <% image = current_user.photo.url ? current_user.photo : "https://res.cloudinary.com/montycat/image/upload/v1520001176/profile-placeholder.png" %>
              <%= cl_image_tag image, class: 'organiser-avatar' %>
            </div>


          </div>
          <div class="location-details">
            <div class="location">
              <h4>Event location:</h4>
              <p><%= @event.address %></p>
              <p><%= @event.postcode %></p>
            </div>
            <div class="date">
              <h4>Event Date</h4>
              <% if @event.start_date == @event.end_date %>
              <p>This event takes place on <%= @event.start_date.strftime('%d/%m/%Y') %></p>
              <% else %>
              <p>This event takes place between <%= @event.start_date.strftime('%d/%m/%Y') %> and <%= @event.end_date.strftime('%d/%m/%Y') %></p></p>
              <% end %>
            </div>
          </div>
          <p class='event-description'><%= @event.description %></p>
        </div>
        <div class="event-details">
          <div class="event-category">
            <h4>Event Topics & Style:</h4>
            <ul>
              <% @event.categories.each do |category| %>
              <li><%= category.name %></li>
              <% end %>
            </ul>
          </div>
<!--           <div class="event-type">
            <h5>This event is <%#= ['A', 'E', 'I', 'O', 'U' ].include?(@event.talk_type[0]) ? 'an' : 'a'  %> <%#= @event.talk_type.downcase %></h5>
          </div> -->
        </div>
        <div class="event-list">
          <div class="event-item">
            <p><i class="fas fa-pound-sign fa-fw"></i>This event is <%= @event.is_paid ? 'a for-profit event' : 'free' %></p>
            <p><i class="fas fa-bed fa-fw"></i>This event's organiser <%= @event.expenses_hotels ? 'will' : 'won\'t' %> pay for a hotel</p>
          </div>
          <div class="event-item">
            <p><i class="fas fa-plane fa-fw"></i>This event's organiser <%= @event.expenses_flights ? 'will' : 'won\'t' %> pay for transport</p>
            <p><i class="fas fa-utensils fa-fw"></i>This event's organiser <%= @event.expenses_per_diems ? 'will' : 'won\'t' %> pay for per diems</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div class="location-container">
        <div class="map-event">
          <%= render 'shared/map-event' %>
        </div>
      </div>
    </div>
  </div>
</div>


<%#= link_to 'Accept', invites_accept_path(@event.invites.select(user: current_user)), class: 'btn btn-success', method: 'patch' %>
<%#= link_to 'Reject', invites_reject_path(@event.invites.select(user: current_user)), class: 'btn btn-danger', method: 'patch' %>

app/views/events/show.html.erb
<div class="page-container">

  <div class="page-card-container">
    <h4><%= @event.name.titleize %></h4>
    <div class="organiser">
      <p>Organised by <%= @event.user.first_name %>  <%= @event.user.last_name %></p>
      <% image = current_user.photo.url ? current_user.photo : "https://res.cloudinary.com/montycat/image/upload/v1520001176/profile-placeholder.png" %>
      <%= cl_image_tag image, class: 'organiser-avatar' %>
    </div>
    <div class="date">
      <% if @event.start_date == @event.end_date %>
      <p>This event takes place on <%= @event.start_date.strftime('%d/%m/%Y') %></p>
      <% else %>
      <p>This event takes place between <%= @event.start_date.strftime('%d/%m/%Y') %> and <%= @event.end_date.strftime('%d/%m/%Y') %></p></p>
      <% end %>
    </div>
    <% if current_user == @event.user %>
    <div>
      <%= link_to "Edit Event", edit_event_path, class: 'spker-blue-btn' %>
    </div>
  </div>

  <div class="page-card-container">
    <h4>Speakers</h4>
    <div class="invitees-list">
      <% if @event.invites.length == 0 %>
        <p>No speakers are currently invited to this event. Click 'find speakers' to search for some</p>
      <% else %>
        <% @event.invites.each do |inv| %>
        <% spker = inv.user %>
        <% spker_image = inv.user.photo.url ?inv.user.photo : "https://res.cloudinary.com/montycat/image/upload/v1520001176/profile-placeholder.png" %>
        <div class="invitees">
          <div class="inv-name">
            <div class="avatar" data-toggle="dropdown" style="background-image: url('<%= cl_image_path spker_image, secure: "true" %>')">
            </div>
            <h5><%= spker.first_name %> <%= spker.last_name %></h5>
          </div>
          <div class="inv-detail">
            <% case inv.status %>
            <% when "accepted" %>
            <p class="accepted"><%= inv.status.capitalize %></p>
            <% when "sent" %>
            <p class="sent"><%= inv.status.capitalize %></p>
            <% when "rejected" %>
            <p class="rejected"><%= inv.status.capitalize %></p>
            <% when "counter" %>
            <p class="counter"><%= inv.status.capitalize %></p>
            <% end %>
            <p><%= number_to_currency(inv.fee, unit: "£") %></p>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
    <% else %>
    <div class="booking_button">
      <button class="spker-red-btn" data-toggle="modal" data-target="#event_quote_modal">Send Quote</button>
    </div>
    <% end %>
    <%= link_to "Find Speakers", speakers_path, class: 'spker-red-btn'%>
  </div>

  <div class="page-card-container">
    <h4>Event Topics & Style</h4>
    <ul>
      <% @event.categories.each do |category| %>
      <li>- <%= category.name %></li>
      <% end %>
    </ul>
  </div>

  <div class="page-card-container">
    <h4>Event Conditions</h4>
    <div class="event-list">
      <div class="event-item">
        <p class="<%= @event.is_paid ? 'true' : 'false' %>"><i class="fas fa-pound-sign fa-fw"></i>    Event is <%= @event.is_paid ? 'for profit' : 'free' %></p>
        <p class="<%= @event.expenses_hotels ? 'true' : 'false' %>"><i class="fas fa-bed fa-fw"></i>    Accommodation <%= @event.expenses_hotels ? 'is' : 'is not' %> covered</p>
      </div>
      <div class="event-item">
        <p class="<%= @event.expenses_flights ? 'true' : 'false' %>"><i class="fas fa-plane fa-fw"></i>    Flights <%= @event.expenses_flights ? 'are' : 'aren\'t' %> covered</p>
        <p class="<%= @event.expenses_per_diems ? 'true' : 'false' %>"><i class="fas fa-utensils fa-fw"></i>    Per diems <%= @event.expenses_per_diems ? 'are' : 'aren\'t' %> covered</p>
      </div>
    </div>
  </div>


  <div class="page-card-container map">
    <div class="event-address">
      <h4>Event Address</h4>
      <p><%= @event.address.titleize %>, <%= @event.postcode.upcase %></p>
    </div>
    <%= render 'shared/map-event' %>
  </div>
</div>